apiVersion: v1
kind: Service
metadata:
  name: phonebook-service
spec:
  type: NodePort
  selector:
    component: phonebook-microservice
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31515
  